/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings` (hash: 8061a22181601cdc9a5721bce5ec51ea)
// Runtime types generated with workerd@1.20250712.0 2025-07-18
declare namespace Cloudflare {
  interface Env {
    KV: KVNamespace;
    UPSTASH_REDIS_REST_URL: "https://eager-raven-45538.upstash.io";
    UPSTASH_REDIS_REST_TOKEN: "AbHiACQgMzRjYWI4ZTEtMTI5ZS00ZWQyLTgyZTktMDE1MTU1ZTBhMDNhNWQ4YzVjNTA2ZDEzNDY1YTllYTk4NzA1YzI0ZGIzNDk=";
    BETTER_AUTH_SECRET: "smooth-criminal";
    BETTER_AUTH_URL: "https://steam-be.yogyy.workers.dev";
    AUTH_GITHUB_ID: "4fcdc99ebb93aa62e6cc";
    AUTH_GITHUB_SECRET: "be22b65d850d5c69a0c4fb9122b31cbbba14b20c";
    DB: D1Database;
  }
}
interface CloudflareBindings extends Cloudflare.Env {}
