/* eslint-disable */
// Generated by Wrangler by running `wrangler types --env-interface CloudflareBindings` (hash: 801280aeeaf0d080d85af039fe788ff4)
// Runtime types generated with workerd@1.20250712.0 2025-07-18
declare namespace Cloudflare {
  interface Env {
    UPSTASH_REDIS_REST_URL: string;
    UPSTASH_REDIS_REST_TOKEN: string;
    BETTER_AUTH_SECRET: string;
    BETTER_AUTH_URL: string;
    AUTH_GITHUB_ID: string;
    AUTH_GITHUB_SECRET: string;
    DB: D1Database;
    ASSETS: Fetcher;
  }
}
interface CloudflareBindings extends Cloudflare.Env {}
